export default function handler(req, res) {
    res.status(200).json({
        data: [
            {
                id: 1,
                img: "/assets/images/property/fp1.jpg",
                price: "13000",
                type: "Apartment",
                title: "Luxury Family Home",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Sale"],
                garages: "yes",
                itemDetails: [
                    {
                        name: "Beds",
                        number: "1",
                    },
                    {
                        name: "Baths",
                        number: "1",
                    },
                    {
                        name: "SqFt",
                        number: "8280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                built: "2013",
                amenities: "air-conditioning",
                featured: "sale",
                created_at: 1667181268893,
            },
            {
                id: 2,
                img: "/assets/images/property/fp2.jpg",
                price: "14000",
                type: "Bungalow",
                title: "Renovated Apartment",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                garages: "no",
                itemDetails: [
                    {
                        name: "Beds",
                        number: "2",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                built: "2014",
                amenities: "barbeque",
                featured: "rent",
                created_at: 1667181256361,
            },
            {
                id: 3,
                img: "/assets/images/property/fp3.jpg",
                price: "13000",
                type: "Bungalow",
                title: "Single Family Home",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                garages: "others",
                itemDetails: [
                    {
                        name: "Beds",
                        number: "3",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "3280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                built: "2015",
                amenities: "gym",
                featured: "sale",
                created_at: 1667181247152,
            },
            {
                id: 4,
                img: "/assets/images/property/fp15.jpg",
                price: "11000",
                type: "House",
                title: "Gorgeous Villa Bay View",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "5",
                    },
                    {
                        name: "Baths",
                        number: "5",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],

                amenities: "microwave",
                built: "2016",
                featured: "rent",
                created_at: 1667181237171,
            },
            {
                id: 5,
                img: "/assets/images/property/fp16.jpg",
                price: "17000",
                type: "Land",
                title: "Renovated Apartment",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "4",
                    },
                    {
                        name: "SqFt",
                        number: "6280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                amenities: "tv-cable",
                built: "2017",
                featured: "rent",
                created_at: 1667181227087,
            },
            {
                id: 6,
                img: "/assets/images/property/fp17.jpg",
                price: "16000",
                type: "Single Family Home",
                title: "Gorgeous Villa Bay View",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "9500",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                amenities: "lawn",
                built: "2018",
                featured: "sale",
                created_at: 1667181205309,
            },
            {
                id: 7,
                img: "/assets/images/property/fp18.jpg",
                price: "15000",
                type: "Apartment",
                title: "Renovated Apartment",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "3",
                    },
                    {
                        name: "SqFt",
                        number: "10280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                amenities: "refrigerator",
                built: "2019",
                featured: "rent",
                created_at: 1667181198782,
            },
            {
                id: 8,
                img: "/assets/images/property/fp19.jpg",
                price: "12000",
                type: "Condo",
                title: "Gorgeous Villa Bay View",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "6880",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                amenities: "swimming-pool",
                built: "2020",
                featured: "sale",
                created_at: 1667181187720,
            },
            {
                id: 9,
                img: "/assets/images/property/fp20.jpg",
                price: "14000",
                type: "Single Family Home",
                title: "Renovated Apartment",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "6",
                    },
                    {
                        name: "SqFt",
                        number: "12000",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                amenities: "wifi",
                built: "2015",
                featured: "rent",
                created_at: 1667181163727,
            },
            {
                id: 10,
                img: "/assets/images/property/fp15.jpg",
                price: "15000",
                type: "Apartment",
                title: "Luxury Family Home",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "6",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                amenities: "air-conditioning",
                built: "2012",
                featured: "sale",
                created_at: 1667181156234,
            },
            {
                id: 11,
                img: "/assets/images/property/fp16.jpg",
                price: "19000",
                type: "Villa",
                title: "Renovated Apartment",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "1",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                built: "2014",
                amenities: "barbeque",
                featured: "rent",
                garages: "yes",
                created_at: 1667181146379,
            },
            {
                id: 12,
                img: "/assets/images/property/fp17.jpg",
                price: "13000",
                type: "Bungalow",
                title: "Luxury Family Home",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                built: "2015",
                amenities: "gym",
                featured: "sale",
                garages: "no",
                created_at: 1667181136297,
            },
            {
                id: 13,
                img: "/assets/images/property/fp4.jpg",
                price: "11000",
                type: "Apartment",
                title: "Renovated Apartment",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "3",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                built: "2016",
                amenities: "microwave",
                featured: "rent",
                garages: "others",
                created_at: 1667181125210,
            },
            {
                id: 14,
                img: "/assets/images/property/fp5.jpg",
                price: "13000",
                type: "Condo",
                title: "Luxury Family Home",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "4",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                built: "2017",
                amenities: "tv-cable",
                garages: "yes",
                featured: "sale",
                created_at: 1667181115744,
            },
            {
                id: 15,
                img: "/assets/images/property/fp6.jpg",
                price: "17000",
                type: "Single Family Home",
                title: "Renovated Apartment",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "5",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                built: "2018",
                amenities: "lawn",
                featured: "rent",
                garages: "no",
                created_at: 1667181101258,
            },
            {
                id: 16,
                img: "/assets/images/property/fp10.jpg",
                price: "16000",
                type: "House",
                title: "Renovated Apartment",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "6",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                built: "2020",
                amenities: "refrigerator",
                featured: "sale",
                garages: "yes",
                created_at: 1667181087711,
            },
            {
                id: 17,
                img: "/assets/images/property/fp11.jpg",
                price: "14000",
                type: "Apartment",
                title: "Land",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                garages: "others",
                featured: "rent",
                created_at: 1667181077261,
            },
            {
                id: 18,
                img: "/assets/images/property/fp12.jpg",
                price: "13000",
                type: "Villa",
                title: "Renovated Apartment",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],

                featured: "sale",
                created_at: 1667181067584,
            },
            {
                id: 19,
                img: "/assets/images/property/fp13.jpg",
                price: "12000",
                type: "Single Family Home",
                title: "Luxury Family Home",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                featured: "rent",
                created_at: 1667181056952,
            },
            {
                id: 20,
                img: "/assets/images/property/fp14.jpg",
                price: "11000",
                type: "Single Family Home",
                title: "Renovated Apartment",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],

                featured: "sale",
                created_at: 1667181046672,
            },
            {
                id: 21,
                img: "/assets/images/property/fp12.jpg",
                price: "17000",
                type: "Villa",
                title: "Renovated Apartment",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],

                featured: "rent",
                created_at: 1667181029933,
            },
            {
                id: 22,
                img: "/assets/images/property/fp1.jpg",
                price: "14000",
                type: "Single Family Home",
                title: "Sweet Family Home",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],

                featured: "sale",
                created_at: 1667181019333,
            },
            {
                id: 23,
                img: "/assets/images/property/fp2.jpg",
                price: "12000",
                type: "Apartment",
                title: "Renovated Apartment",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],

                featured: "rent",
                created_at: 1667181005044,
            },
            {
                id: 24,
                img: "/assets/images/property/fp3.jpg",
                price: "13000",
                type: "Villa",
                title: "Luxury Family Home",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                featured: "sale",
                created_at: 1667180992984,
            },
            {
                id: 25,
                img: "/assets/images/property/fp7.jpg",
                price: "11000",
                type: "Single Family Home",
                title: "Renovated Apartment",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],

                featured: "sale",
                created_at: 1667180981746,
            },
            {
                id: 26,
                img: "/assets/images/property/fp8.jpg",
                price: "13000",
                type: "Single Family Home",
                title: "Luxury Family Home",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],

                featured: "rent",
                created_at: 1667180970308,
            },
            {
                id: 27,
                img: "/assets/images/property/fp9.jpg",
                price: "18000",
                type: "Villa",
                title: "Renovated Apartment",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],

                featured: "sale",
                created_at: 1667180956053,
            },
            {
                id: 28,
                img: "/assets/images/property/fp4.jpg",
                price: "19000",
                type: "",
                title: "Luxury Family Home",
                location: ``,
                saleTag: [],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "",
                posterName: "",
                postedYear: "",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                featured: "rent",
                created_at: 1667180944839,
            },
            {
                id: 29,
                img: "/assets/images/property/fp5.jpg",
                price: "12000",
                type: "Apartment",
                title: "Luxury Family Home",
                location: ``,
                saleTag: [],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "",
                posterName: "",
                postedYear: "",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],

                featured: "sale",
                created_at: 1667180933456,
            },
            {
                id: 30,
                img: "/assets/images/property/fp7.jpg",
                price: "11000",
                type: "Apartment",
                title: "Renovated Apartment",
                location: ``,
                saleTag: [],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "",
                posterName: "",
                postedYear: "",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                built: "2014",
                amenities: "air-conditioning",
                featured: "rent",
                created_at: 1667180920571,
            },
            {
                id: 31,
                img: "/assets/images/property/fp21.jpg",
                price: "11000",
                type: "Apartment",
                title: "Gorgeous Villa Bay View",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "1",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                built: "2013",
                amenities: "air-conditioning",
                garages: "yes",
                featured: "sale",
                created_at: 1667180908198,
            },
            {
                id: 32,
                img: "/assets/images/property/fp22.jpg",
                price: "13000",
                type: "Bungalow",
                title: "Renovated Apartment",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                built: "2015",
                amenities: "barbeque",
                garages: "no",
                featured: "rent",
                created_at: 1667180896056,
            },
            {
                id: 33,
                img: "/assets/images/property/fp23.jpg",
                price: "18000",
                type: "Condo",
                title: "Gorgeous Villa Bay View",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: ["Featured", "For Rent"],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "3",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "/assets/images/property/pposter1.png",
                posterName: "Ali Tufan",
                postedYear: "1 year ago",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                built: "2014",
                amenities: "gym",
                featured: "sale",
                garages: "Others",
                created_at: 1667180884778,
            },
            {
                id: 34,
                img: "/assets/images/property/fp24.jpg",
                price: "19000",
                type: "House",
                title: "Gorgeous Villa Bay View",
                location: ``,
                saleTag: [],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "4",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "",
                posterName: "",
                postedYear: "",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                built: "2015",
                amenities: "microwave",
                featured: "sale",
                garages: "yes",
                created_at: 1667180868495,
            },
            {
                id: 35,
                img: "/assets/images/property/fp25.jpg",
                price: "12000",
                type: "Land",
                title: "Renovated Apartment",
                location: ``,
                saleTag: [],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "5",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "",
                posterName: "",
                postedYear: "",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                built: "2016",
                amenities: "tv-cable",
                garages: "no",
                featured: "rent",
                created_at: 1667180858318,
            },
            {
                id: 36,
                img: "/assets/images/property/fp26.jpg",
                price: "11000",
                type: "Single Family",
                title: "Gorgeous Villa Bay View",
                location: ``,
                saleTag: [],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "6",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "",
                posterName: "",
                postedYear: "",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                built: "2017",
                amenities: "lawn",
                featured: "sale",
                garages: "others",
                created_at: 1667180846604,
            },
            {
                id: 37,
                img: "/assets/images/property/1.jpg",
                price: "11000",
                type: "",
                title: "Gorgeous Villa Bay View",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: [],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "",
                posterName: "",
                postedYear: "",
                imgList: [
                    "/assets/images/property/2.jpg",
                    "/assets/images/property/3.jpg",
                    "/assets/images/property/4.jpg",
                    "/assets/images/property/5.jpg",
                    "/assets/images/property/6.jpg",
                    "/assets/images/property/7.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                built: "2018",
                amenities: "air-conditioning",
                garages: "yes",
                featured: "rent",
                created_at: 1667180834746,
            },
            {
                id: 38,
                img: "/assets/images/property/ls1.jpg",
                price: "13000",
                type: "",
                title: "Luxury Family Home",
                location: `1421 San Pedro
        St, Los Angeles, CA 900015`,
                saleTag: [],
                itemDetails: [
                    {
                        name: "Beds",
                        number: "4",
                    },
                    {
                        name: "Baths",
                        number: "2",
                    },
                    {
                        name: "SqFt",
                        number: "5280",
                    },
                ],
                posterAvatar: "",
                posterName: "",
                postedYear: "",
                imgList: [],
                imgList2: [
                    "/assets/images/property/ls2.jpg",
                    "/assets/images/property/ls3.jpg",
                    "/assets/images/property/ls4.jpg",
                    "/assets/images/property/ls5.jpg",
                ],
                built: "2014",
                amenities: "barbeque",
                featured: "sale",
                created_at: 1667180799028,
            },
        ],
    });
}
